name: Build and Deploy
run-name: ${{ github.actor }} is started the deployment 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install ng-cli
      run: npm install -g @angular/cli

    - name: Build
      run: ng build --output-path docs --base-href /ng-hr-app/

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/ng-hr-app
        enable_jekyll: true
